### PR TITLE
Import face recognition AAR library

### PR DESCRIPTION
**Pull request by jo-elimu**

### CODE REVIEW

**Review by jo-elimu — COMMENTED** [review]
@schaemik @schaemik This failed. Any ideas?

$ ./gradlew build
Incremental java compilation is an incubating feature.
Defining custom 'build' task when using the standard Gradle lifecycle plugins has been deprecated and is scheduled to be removed in Gradle 3.0
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareChZhawFacerecognitionlibrary111Library FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:prepareChZhawFacerecognitionlibrary111Library'.
  > Could not expand ZIP '/Users/jogrimst/.gradle/caches/modules-2/files-2.1/ch.zhaw/facerecognitionlibrary/1.1.1/5b94a41b3a06cff11e3aac693819e977e3e8d21/facerecognitionlibrary-1.1.1.aar'.

**Comment by jo-elimu** [comment]
Similar error on Travis server: 

Execution failed for task ':app:prepareChZhawFacerecognitionlibrary111Library'.

> Could not expand ZIP '/home/travis/.gradle/caches/modules-2/files-2.1/ch.zhaw/facerecognitionlibrary/1.1.1/5b94a41b3a06cff11e3aac693819e977e3e8d21/facerecognitionlibrary-1.1.1.aar'.

**Comment by jo-elimu** [comment]
When trying to unarchive manually, this message appeared: 

screen shot 2016-10-25 at 22 45 50

**Comment by sladomic** [comment]
For me it works if I take them directly from Jenkins. But if I use the one in Archiva I get the same error.

bildschirmfoto 2016-10-25 um 21 51 39

**Comment by jo-elimu** [comment]
> For me it works if I take them directly from Jenkins. But if I use the one in Archiva I get the same error.

@sladomic  Are the two files different in size?

**Comment by sladomic** [comment]
yes :)

bildschirmfoto 2016-10-25 um 21 55 36

**Comment by sladomic** [comment]
I think I can't merge/approve it until the checks in travis are done?

bildschirmfoto 2016-10-25 um 22 20 46

**Comment by jo-elimu** [comment]
> I think I can't merge/approve it until the checks in travis are done?

That's right. It has to compile without errors first.

**Pull request merged**
