### PR TITLE
Delete StudentImages if the featureExtraction can't be run #236

### PR DESCRIPTION
**Pull request by sladomic**

### CODE REVIEW

**Review by jo-elimu — COMMENTED** [review]
@sladomic What if we at a later point in time would like to back and look at the images for debugging reasons? Instead of actually deleting them from the device/database, what about labelling them as "expired" or just fetching events from the database after a certain date. E.g. only events created during the past 30 days?

**Comment by sladomic** [comment]
@jogrimst I just delete them if a file is missing anyway (so if the feature extraction would fail for a StudentImageCollectionEvent). The files, where the feature extraction was successful will stay on the device. But if you want we can also have an expired flag on the db which I set instead

**Comment by sladomic** [comment]
@jogrimst Now the StudentImageCollectionEvent and all connected StudentImages and StudentImageFeatures will be deleted if
1) a file is missing
2) feature extraction for a StudentImage fails

I just delete them in the db but not the files itself. Should I also delete the files or keep them for debugging?

**Comment by jo-elimu** [comment]
> I just delete them in the db but not the files itself. Should I also delete the files or keep them for debugging?

@sladomic I suggest we keep them, just in case.

**Pull request merged**
